### ISSUE TITLE
Include examples for dohpath -> URI Template construction

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-add/draft-ietf-add-svcb-dns#14]
[Section 5.1](https://datatracker.ietf.org/doc/html/draft-ietf-add-svcb-dns-02#section-5.1) has a good amount of information, but could be improved if there were examples showing how one constructs a URI Template from the relevant $HOST, $PORT, and $DOHPATH parameters. These examples might also include parameters that would yield invalid URLs. [Section 7](https://datatracker.ietf.org/doc/html/draft-ietf-add-svcb-dns-02#section-7) has some examples for the RR contents, as derived from a URI Template, but not how to use those contents to construct URI Templates.

**Comment by bemasc** [comment]
I've changed the description to remove these variables, so hopefully this is now addressed.
